[env:AVR128DA28]
platform = atmelmegaavr
board = AVR128DA28
framework = arduino
monitor_speed = 115200

build_flags =
    -D ENCODER_DO_NOT_USE_INTERRUPTS
    -D ARDUINO_LMIC_PROJECT_CONFIG_H_SUPPRESS
    -D CFG_us915=1
    -D CFG_sx1276_radio=1
    -Os
    -flto
    -ffunction-sections
    -fdata-sections
    -Wl,--gc-sections

; Build options for DxCore
; 24MHz internal oscillator
board_build.f_cpu = 24000000L
board_build.core = dxcore

; Library dependencies
; PlatformIO will automatically download these from the registry
lib_deps =
    adafruit/Adafruit BME280 Library
    adafruit/Adafruit Unified Sensor
    adafruit/Adafruit SSD1306
    adafruit/Adafruit GFX Library
    PaulStoffregen/Encoder
    br3ttb/PID-AutoTune
    mcci-catena/MCCI LoRaWAN LMIC library
