[env:ATtiny3226]
platform = atmelavr
board = ATtiny3226
framework = arduino
monitor_speed = 115200

; Build options for megaTinyCore
; 20MHz internal oscillator
board_build.f_cpu = 20000000L
board_build.core = megaTinyCore

; Library dependencies
; PlatformIO will automatically download these from the registry
lib_deps =
    adafruit/Adafruit BME280 Library
    adafruit/Adafruit Unified Sensor
    adafruit/Adafruit SSD1306
    adafruit/Adafruit GFX Library
